/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workspace.roicomparison;

import ij.ImagePlus;
import ij.gui.Plot;
import ij.gui.Roi;
import ij.text.TextWindow;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import static workspace.roicomparison.RoiCompareSeveral.compareseveralrois;
import static workspace.roicomparison.RoiCompareSeveral.compareseveralroisagainstone;

/**
 *
 * @author joheras
 */
public class RoiMatching extends javax.swing.JDialog {

    /**
     * Creates new form RoiMatching
     */
    private ArrayList<Roi> rois1;
    private ArrayList<Roi> rois2;
    private Roi combinetrueroi;
    private Roi combinehyproi;
    private ImagePlus imp;
    private int max = 0;
    private Plot plot;
    private ArrayList list;

    public RoiMatching(java.awt.Frame parent, boolean modal, ArrayList<Roi> rois1, ArrayList<Roi> rois2, ImagePlus imp, Roi combinetrueroi, Roi combinehyproi, Plot plot, ArrayList list) {
        super(parent, modal);
        initComponents();
        this.rois1 = rois1;
        this.rois2 = rois2;
        this.combinehyproi = combinehyproi;
        this.combinetrueroi = combinetrueroi;
        this.imp = imp;
        this.plot=plot;
        this.list=list;

        max = rois2.size();

        enablechoices();

    }

    private void enablechoices() {
        JComboBox[] trueroischoices = {jcbtrueroi1, jcbtrueroi2, jcbtrueroi3, jcbtrueroi4, jcbtrueroi5, jcbtrueroi6, jcbtrueroi7, jcbtrueroi8, jcbtrueroi9, jcbtrueroi10, jcbtrueroi11, jcbtrueroi12, jcbtrueroi13, jcbtrueroi14, jcbtrueroi15, jcbtrueroi16, jcbtrueroi17, jcbtrueroi18, jcbtrueroi19, jcbtrueroi20, jcbtrueroi21, jcbtrueroi22, jcbtrueroi23, jcbtrueroi24, jcbtrueroi25, jcbtrueroi26, jcbtrueroi27, jcbtrueroi28, jcbtrueroi29, jcbtrueroi30, jcbtrueroi31, jcbtrueroi32, jcbtrueroi33, jcbtrueroi34, jcbtrueroi35, jcbtrueroi36, jcbtrueroi37, jcbtrueroi38, jcbtrueroi39, jcbtrueroi40};
        JComboBox[] hyproischoices = {jcbhypothesisedroi1, jcbhypothesisedroi2, jcbhypothesisedroi3, jcbhypothesisedroi4, jcbhypothesisedroi5, jcbhypothesisedroi6, jcbhypothesisedroi7, jcbhypothesisedroi8, jcbhypothesisedroi9, jcbhypothesisedroi10, jcbhypothesisedroi11, jcbhypothesisedroi12, jcbhypothesisedroi13, jcbhypothesisedroi14, jcbhypothesisedroi15, jcbhypothesisedroi16, jcbhypothesisedroi17, jcbhypothesisedroi18, jcbhypothesisedroi19, jcbhypothesisedroi20, jcbhypothesisedroi21, jcbhypothesisedroi22, jcbhypothesisedroi23, jcbhypothesisedroi24, jcbhypothesisedroi25, jcbhypothesisedroi26, jcbhypothesisedroi27, jcbhypothesisedroi28, jcbhypothesisedroi29, jcbhypothesisedroi30, jcbhypothesisedroi31, jcbhypothesisedroi32, jcbhypothesisedroi33, jcbhypothesisedroi34, jcbhypothesisedroi35, jcbhypothesisedroi36, jcbhypothesisedroi37, jcbhypothesisedroi38, jcbhypothesisedroi39, jcbhypothesisedroi40};
        JLabel[] labels = {jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel18, jLabel19, jLabel20, jLabel21, jLabel22, jLabel23, jLabel24, jLabel25, jLabel26, jLabel27, jLabel28, jLabel29, jLabel30, jLabel31, jLabel32, jLabel33, jLabel34, jLabel35, jLabel36, jLabel37, jLabel38, jLabel39, jLabel40, jLabel41, jLabel42};

        for (int i = max; i < labels.length; i++) {
            trueroischoices[i].setVisible(false);
            hyproischoices[i].setVisible(false);
            labels[i].setVisible(false);
        }

        for (int i = 0; i < max; i++) {

            trueroischoices[i].addItem("");
            hyproischoices[i].addItem("");

            for (int j = 0; j < rois1.size(); j++) {
                trueroischoices[i].addItem(rois1.get(j).getName());
            }
            for (int j = 0; j < rois2.size(); j++) {
                hyproischoices[i].addItem(rois2.get(j).getName());
            }

            if (i < rois1.size()) {
                trueroischoices[i].setSelectedIndex(i + 1);
            }

            if (rois1.size() == 1) {
                trueroischoices[i].setSelectedIndex(1);
            }

            if (i < rois2.size()) {
                hyproischoices[i].setSelectedIndex(i + 1);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbtrueroi1 = new javax.swing.JComboBox();
        jcbhypothesisedroi1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcbtrueroi2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcbhypothesisedroi2 = new javax.swing.JComboBox();
        jcbtrueroi3 = new javax.swing.JComboBox();
        jcbhypothesisedroi3 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jcbtrueroi4 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jcbhypothesisedroi4 = new javax.swing.JComboBox();
        jcbtrueroi5 = new javax.swing.JComboBox();
        jcbhypothesisedroi5 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jcbtrueroi6 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jcbhypothesisedroi6 = new javax.swing.JComboBox();
        jcbtrueroi7 = new javax.swing.JComboBox();
        jcbhypothesisedroi7 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jcbtrueroi8 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jcbhypothesisedroi8 = new javax.swing.JComboBox();
        jcbtrueroi9 = new javax.swing.JComboBox();
        jcbhypothesisedroi9 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jcbtrueroi10 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jcbhypothesisedroi10 = new javax.swing.JComboBox();
        jcbtrueroi11 = new javax.swing.JComboBox();
        jcbhypothesisedroi11 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jcbtrueroi12 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jcbhypothesisedroi12 = new javax.swing.JComboBox();
        jcbtrueroi13 = new javax.swing.JComboBox();
        jcbhypothesisedroi13 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jcbtrueroi14 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jcbhypothesisedroi14 = new javax.swing.JComboBox();
        jcbtrueroi15 = new javax.swing.JComboBox();
        jcbhypothesisedroi15 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jcbtrueroi16 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jcbhypothesisedroi16 = new javax.swing.JComboBox();
        jcbtrueroi17 = new javax.swing.JComboBox();
        jcbhypothesisedroi17 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jcbtrueroi18 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jcbhypothesisedroi18 = new javax.swing.JComboBox();
        jcbtrueroi19 = new javax.swing.JComboBox();
        jcbhypothesisedroi19 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jcbtrueroi20 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jcbhypothesisedroi20 = new javax.swing.JComboBox();
        jcbtrueroi21 = new javax.swing.JComboBox();
        jcbhypothesisedroi21 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jcbtrueroi22 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jcbhypothesisedroi22 = new javax.swing.JComboBox();
        jcbtrueroi23 = new javax.swing.JComboBox();
        jcbhypothesisedroi23 = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jcbtrueroi24 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jcbhypothesisedroi24 = new javax.swing.JComboBox();
        jcbtrueroi25 = new javax.swing.JComboBox();
        jcbhypothesisedroi25 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jcbtrueroi26 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jcbhypothesisedroi26 = new javax.swing.JComboBox();
        jcbtrueroi27 = new javax.swing.JComboBox();
        jcbhypothesisedroi27 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jcbtrueroi28 = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jcbhypothesisedroi28 = new javax.swing.JComboBox();
        jcbtrueroi29 = new javax.swing.JComboBox();
        jcbhypothesisedroi29 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jcbtrueroi30 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jcbhypothesisedroi30 = new javax.swing.JComboBox();
        jcbtrueroi31 = new javax.swing.JComboBox();
        jcbhypothesisedroi31 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jcbtrueroi32 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jcbhypothesisedroi32 = new javax.swing.JComboBox();
        jcbtrueroi33 = new javax.swing.JComboBox();
        jcbhypothesisedroi33 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jcbtrueroi34 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jcbhypothesisedroi34 = new javax.swing.JComboBox();
        jcbtrueroi35 = new javax.swing.JComboBox();
        jcbhypothesisedroi35 = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jcbtrueroi36 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jcbhypothesisedroi36 = new javax.swing.JComboBox();
        jcbtrueroi37 = new javax.swing.JComboBox();
        jcbhypothesisedroi37 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jcbtrueroi38 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jcbhypothesisedroi38 = new javax.swing.JComboBox();
        jcbtrueroi39 = new javax.swing.JComboBox();
        jcbhypothesisedroi39 = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jcbtrueroi40 = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jcbhypothesisedroi40 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcboptions = new javax.swing.JComboBox();
        jcbaddres = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("True ROI");

        jLabel2.setText("Hypothesised ROI");

        jLabel3.setText("<->");

        jLabel4.setText("<->");

        jLabel5.setText("<->");

        jLabel6.setText("<->");

        jLabel7.setText("<->");

        jLabel8.setText("<->");

        jLabel9.setText("<->");

        jLabel10.setText("<->");

        jLabel11.setText("<->");

        jLabel12.setText("<->");

        jLabel13.setText("<->");

        jLabel14.setText("<->");

        jLabel15.setText("<->");

        jLabel16.setText("<->");

        jLabel17.setText("<->");

        jLabel18.setText("<->");

        jLabel19.setText("<->");

        jLabel20.setText("<->");

        jLabel21.setText("<->");

        jLabel22.setText("<->");

        jLabel23.setText("<->");

        jLabel24.setText("<->");

        jLabel25.setText("<->");

        jLabel26.setText("<->");

        jLabel27.setText("<->");

        jLabel28.setText("<->");

        jLabel29.setText("<->");

        jLabel30.setText("<->");

        jLabel31.setText("<->");

        jLabel32.setText("<->");

        jLabel33.setText("<->");

        jLabel34.setText("<->");

        jLabel35.setText("<->");

        jLabel36.setText("<->");

        jLabel37.setText("<->");

        jLabel38.setText("<->");

        jLabel39.setText("<->");

        jLabel40.setText("<->");

        jLabel41.setText("<->");

        jLabel42.setText("<->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcbhypothesisedroi1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi3, 0, 120, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi6, 0, 120, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi9, 0, 120, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbhypothesisedroi10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jcbhypothesisedroi9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi12, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi14, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi14, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi19, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi19, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi20, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi21, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi22, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi23, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi23, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi24, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi25, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbhypothesisedroi26, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jcbhypothesisedroi25, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi27, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi27, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi28, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi30, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi29, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi30, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi31, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi31, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi32, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbtrueroi15, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbtrueroi16, 0, 120, Short.MAX_VALUE)
                                    .addComponent(jcbtrueroi17, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi17, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi15, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi16, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi18, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel35)
                        .addGap(171, 171, 171))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi33, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi34, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbhypothesisedroi34, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jcbhypothesisedroi33, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi35, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi36, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi35, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi36, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi38, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcbtrueroi37, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel39)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi37, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi38, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtrueroi39, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbtrueroi40, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbhypothesisedroi39, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbhypothesisedroi40, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbtrueroi18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbhypothesisedroi18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbtrueroi40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbhypothesisedroi40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)))
        );

        jScrollPane1.setViewportView(jPanel1);

        jButton1.setText("Evaluate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jcboptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Match regions", "Combine regions in a unique region", "Hypothesised rois are points" }));
        jcboptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboptionsActionPerformed(evt);
            }
        });

        jcbaddres.setText("Add results to previous data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcboptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jcbaddres, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcboptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbaddres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ArrayList<Roi> newrois1 = new ArrayList<>();
        ArrayList<Roi> newrois2 = new ArrayList<>();
        ArrayList<Roi> notincludedrois = new ArrayList<>();
        JComboBox[] trueroischoices = {jcbtrueroi1, jcbtrueroi2, jcbtrueroi3, jcbtrueroi4, jcbtrueroi5, jcbtrueroi6, jcbtrueroi7, jcbtrueroi8, jcbtrueroi9, jcbtrueroi10, jcbtrueroi11, jcbtrueroi12, jcbtrueroi13, jcbtrueroi14, jcbtrueroi15, jcbtrueroi16, jcbtrueroi17, jcbtrueroi18, jcbtrueroi19, jcbtrueroi20, jcbtrueroi21, jcbtrueroi22, jcbtrueroi23, jcbtrueroi24, jcbtrueroi25, jcbtrueroi26, jcbtrueroi27, jcbtrueroi28, jcbtrueroi29, jcbtrueroi30, jcbtrueroi31, jcbtrueroi32, jcbtrueroi33, jcbtrueroi34, jcbtrueroi35, jcbtrueroi36, jcbtrueroi37, jcbtrueroi38, jcbtrueroi39, jcbtrueroi40};
        JComboBox[] hyproischoices = {jcbhypothesisedroi1, jcbhypothesisedroi2, jcbhypothesisedroi3, jcbhypothesisedroi4, jcbhypothesisedroi5, jcbhypothesisedroi6, jcbhypothesisedroi7, jcbhypothesisedroi8, jcbhypothesisedroi9, jcbhypothesisedroi10, jcbhypothesisedroi11, jcbhypothesisedroi12, jcbhypothesisedroi13, jcbhypothesisedroi14, jcbhypothesisedroi15, jcbhypothesisedroi16, jcbhypothesisedroi17, jcbhypothesisedroi18, jcbhypothesisedroi19, jcbhypothesisedroi20, jcbhypothesisedroi21, jcbhypothesisedroi22, jcbhypothesisedroi23, jcbhypothesisedroi24, jcbhypothesisedroi25, jcbhypothesisedroi26, jcbhypothesisedroi27, jcbhypothesisedroi28, jcbhypothesisedroi29, jcbhypothesisedroi30, jcbhypothesisedroi31, jcbhypothesisedroi32, jcbhypothesisedroi33, jcbhypothesisedroi34, jcbhypothesisedroi35, jcbhypothesisedroi36, jcbhypothesisedroi37, jcbhypothesisedroi38, jcbhypothesisedroi39, jcbhypothesisedroi40};

        int option = jcboptions.getSelectedIndex();
        switch (option) {
            case 0:

                for (int i = 0; i < max; i++) {

                    if (trueroischoices[i].getSelectedIndex() != 0
                            && hyproischoices[i].getSelectedIndex() != 0) {
                        newrois1.add(rois1.get(trueroischoices[i].getSelectedIndex() - 1));
                        newrois2.add(rois2.get(hyproischoices[i].getSelectedIndex() - 1));
                    } else if (trueroischoices[i].getSelectedIndex() == 0) {

                        newrois1.add(new Roi(0, 0, 0, 0));
                        newrois2.add(rois2.get(hyproischoices[i].getSelectedIndex() - 1));
                    } else {
                        newrois1.add(rois1.get(trueroischoices[i].getSelectedIndex() - 1));
                        newrois2.add(new Roi(0, 0, 0, 0));
                    }
                }
                
                for(Roi r : rois1){
                    if(!newrois1.contains(r)){
                        notincludedrois.add(r);
                    }
                
                }
                
                this.dispose();

                if (rois1.size() == 1) {
                    if(jcbaddres.isSelected()){
                        compareseveralroisagainstone(newrois1, newrois2, imp,plot,list);
                        String headings = "Index\tLabel\tTrue ROI\tHypothesised ROI\tTrue positive\tFalse Positive\tTrue negative\tFalse negative\tPositive\tNegative\tAccuracy\tPrecision\tRecall\tFallout\tSensitivity\tSpecifity\tNegative predictive value\tFalse discovery rate\tFalse negative rate\tLR+\tLR-\tF-measure alpha=0.5\tF-measure alpha=1\tF-measure alpha=2";
                        TextWindow textWindow = new TextWindow("Measurements", headings, list, 600, 400);
                        plot.show();
                    }else{
                        compareseveralroisagainstone(newrois1, newrois2, imp);
                    }    
                } else {
                    if(jcbaddres.isSelected()){
                       compareseveralrois(newrois1, newrois2,notincludedrois, imp,plot,list);
                    }else{
                        compareseveralrois(newrois1, newrois2,notincludedrois, imp);
                    }
                    
                }
                break;
            case 1:
                newrois1.add(combinetrueroi);
                newrois2.add(combinehyproi);
                this.dispose();
                 if(jcbaddres.isSelected()){
                        compareseveralroisagainstone(newrois1, newrois2, imp,plot,list);
                    }else{
                        compareseveralroisagainstone(newrois1, newrois2, imp);
                    }
                break;
            case 2:
                this.dispose();
                RoiCompareSeveralPointsHorizontal rc = new RoiCompareSeveralPointsHorizontal(rois1, rois2, imp);
                rc.comparerois();
                break;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcboptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboptionsActionPerformed
        int option = jcboptions.getSelectedIndex();

        switch (option) {
            case 0:
                enableall();
                jcbaddres.setEnabled(true);
                break;
            case 1:
                disableall();
                jcbaddres.setEnabled(true);
                break;
            case 2:
                disableall();
                jcbaddres.setEnabled(false);
                break;
        }


    }//GEN-LAST:event_jcboptionsActionPerformed

    private void enableall() {
        JComboBox[] trueroischoices = {jcbtrueroi1, jcbtrueroi2, jcbtrueroi3, jcbtrueroi4, jcbtrueroi5, jcbtrueroi6, jcbtrueroi7, jcbtrueroi8, jcbtrueroi9, jcbtrueroi10, jcbtrueroi11, jcbtrueroi12, jcbtrueroi13, jcbtrueroi14, jcbtrueroi15, jcbtrueroi16, jcbtrueroi17, jcbtrueroi18, jcbtrueroi19, jcbtrueroi20, jcbtrueroi21, jcbtrueroi22, jcbtrueroi23, jcbtrueroi24, jcbtrueroi25, jcbtrueroi26, jcbtrueroi27, jcbtrueroi28, jcbtrueroi29, jcbtrueroi30, jcbtrueroi31, jcbtrueroi32, jcbtrueroi33, jcbtrueroi34, jcbtrueroi35, jcbtrueroi36, jcbtrueroi37, jcbtrueroi38, jcbtrueroi39, jcbtrueroi40};
        JComboBox[] hyproischoices = {jcbhypothesisedroi1, jcbhypothesisedroi2, jcbhypothesisedroi3, jcbhypothesisedroi4, jcbhypothesisedroi5, jcbhypothesisedroi6, jcbhypothesisedroi7, jcbhypothesisedroi8, jcbhypothesisedroi9, jcbhypothesisedroi10, jcbhypothesisedroi11, jcbhypothesisedroi12, jcbhypothesisedroi13, jcbhypothesisedroi14, jcbhypothesisedroi15, jcbhypothesisedroi16, jcbhypothesisedroi17, jcbhypothesisedroi18, jcbhypothesisedroi19, jcbhypothesisedroi20, jcbhypothesisedroi21, jcbhypothesisedroi22, jcbhypothesisedroi23, jcbhypothesisedroi24, jcbhypothesisedroi25, jcbhypothesisedroi26, jcbhypothesisedroi27, jcbhypothesisedroi28, jcbhypothesisedroi29, jcbhypothesisedroi30, jcbhypothesisedroi31, jcbhypothesisedroi32, jcbhypothesisedroi33, jcbhypothesisedroi34, jcbhypothesisedroi35, jcbhypothesisedroi36, jcbhypothesisedroi37, jcbhypothesisedroi38, jcbhypothesisedroi39, jcbhypothesisedroi40};

        for (JComboBox j : trueroischoices) {
            j.setEnabled(true);
        }

        for (JComboBox j : hyproischoices) {
            j.setEnabled(true);
        }

    }

    private void disableall() {
        JComboBox[] trueroischoices = {jcbtrueroi1, jcbtrueroi2, jcbtrueroi3, jcbtrueroi4, jcbtrueroi5, jcbtrueroi6, jcbtrueroi7, jcbtrueroi8, jcbtrueroi9, jcbtrueroi10, jcbtrueroi11, jcbtrueroi12, jcbtrueroi13, jcbtrueroi14, jcbtrueroi15, jcbtrueroi16, jcbtrueroi17, jcbtrueroi18, jcbtrueroi19, jcbtrueroi20, jcbtrueroi21, jcbtrueroi22, jcbtrueroi23, jcbtrueroi24, jcbtrueroi25, jcbtrueroi26, jcbtrueroi27, jcbtrueroi28, jcbtrueroi29, jcbtrueroi30, jcbtrueroi31, jcbtrueroi32, jcbtrueroi33, jcbtrueroi34, jcbtrueroi35, jcbtrueroi36, jcbtrueroi37, jcbtrueroi38, jcbtrueroi39, jcbtrueroi40};
        JComboBox[] hyproischoices = {jcbhypothesisedroi1, jcbhypothesisedroi2, jcbhypothesisedroi3, jcbhypothesisedroi4, jcbhypothesisedroi5, jcbhypothesisedroi6, jcbhypothesisedroi7, jcbhypothesisedroi8, jcbhypothesisedroi9, jcbhypothesisedroi10, jcbhypothesisedroi11, jcbhypothesisedroi12, jcbhypothesisedroi13, jcbhypothesisedroi14, jcbhypothesisedroi15, jcbhypothesisedroi16, jcbhypothesisedroi17, jcbhypothesisedroi18, jcbhypothesisedroi19, jcbhypothesisedroi20, jcbhypothesisedroi21, jcbhypothesisedroi22, jcbhypothesisedroi23, jcbhypothesisedroi24, jcbhypothesisedroi25, jcbhypothesisedroi26, jcbhypothesisedroi27, jcbhypothesisedroi28, jcbhypothesisedroi29, jcbhypothesisedroi30, jcbhypothesisedroi31, jcbhypothesisedroi32, jcbhypothesisedroi33, jcbhypothesisedroi34, jcbhypothesisedroi35, jcbhypothesisedroi36, jcbhypothesisedroi37, jcbhypothesisedroi38, jcbhypothesisedroi39, jcbhypothesisedroi40};

        for (JComboBox j : trueroischoices) {
            j.setEnabled(false);
        }

        for (JComboBox j : hyproischoices) {
            j.setEnabled(false);
        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbaddres;
    private javax.swing.JComboBox jcbhypothesisedroi1;
    private javax.swing.JComboBox jcbhypothesisedroi10;
    private javax.swing.JComboBox jcbhypothesisedroi11;
    private javax.swing.JComboBox jcbhypothesisedroi12;
    private javax.swing.JComboBox jcbhypothesisedroi13;
    private javax.swing.JComboBox jcbhypothesisedroi14;
    private javax.swing.JComboBox jcbhypothesisedroi15;
    private javax.swing.JComboBox jcbhypothesisedroi16;
    private javax.swing.JComboBox jcbhypothesisedroi17;
    private javax.swing.JComboBox jcbhypothesisedroi18;
    private javax.swing.JComboBox jcbhypothesisedroi19;
    private javax.swing.JComboBox jcbhypothesisedroi2;
    private javax.swing.JComboBox jcbhypothesisedroi20;
    private javax.swing.JComboBox jcbhypothesisedroi21;
    private javax.swing.JComboBox jcbhypothesisedroi22;
    private javax.swing.JComboBox jcbhypothesisedroi23;
    private javax.swing.JComboBox jcbhypothesisedroi24;
    private javax.swing.JComboBox jcbhypothesisedroi25;
    private javax.swing.JComboBox jcbhypothesisedroi26;
    private javax.swing.JComboBox jcbhypothesisedroi27;
    private javax.swing.JComboBox jcbhypothesisedroi28;
    private javax.swing.JComboBox jcbhypothesisedroi29;
    private javax.swing.JComboBox jcbhypothesisedroi3;
    private javax.swing.JComboBox jcbhypothesisedroi30;
    private javax.swing.JComboBox jcbhypothesisedroi31;
    private javax.swing.JComboBox jcbhypothesisedroi32;
    private javax.swing.JComboBox jcbhypothesisedroi33;
    private javax.swing.JComboBox jcbhypothesisedroi34;
    private javax.swing.JComboBox jcbhypothesisedroi35;
    private javax.swing.JComboBox jcbhypothesisedroi36;
    private javax.swing.JComboBox jcbhypothesisedroi37;
    private javax.swing.JComboBox jcbhypothesisedroi38;
    private javax.swing.JComboBox jcbhypothesisedroi39;
    private javax.swing.JComboBox jcbhypothesisedroi4;
    private javax.swing.JComboBox jcbhypothesisedroi40;
    private javax.swing.JComboBox jcbhypothesisedroi5;
    private javax.swing.JComboBox jcbhypothesisedroi6;
    private javax.swing.JComboBox jcbhypothesisedroi7;
    private javax.swing.JComboBox jcbhypothesisedroi8;
    private javax.swing.JComboBox jcbhypothesisedroi9;
    private javax.swing.JComboBox jcboptions;
    private javax.swing.JComboBox jcbtrueroi1;
    private javax.swing.JComboBox jcbtrueroi10;
    private javax.swing.JComboBox jcbtrueroi11;
    private javax.swing.JComboBox jcbtrueroi12;
    private javax.swing.JComboBox jcbtrueroi13;
    private javax.swing.JComboBox jcbtrueroi14;
    private javax.swing.JComboBox jcbtrueroi15;
    private javax.swing.JComboBox jcbtrueroi16;
    private javax.swing.JComboBox jcbtrueroi17;
    private javax.swing.JComboBox jcbtrueroi18;
    private javax.swing.JComboBox jcbtrueroi19;
    private javax.swing.JComboBox jcbtrueroi2;
    private javax.swing.JComboBox jcbtrueroi20;
    private javax.swing.JComboBox jcbtrueroi21;
    private javax.swing.JComboBox jcbtrueroi22;
    private javax.swing.JComboBox jcbtrueroi23;
    private javax.swing.JComboBox jcbtrueroi24;
    private javax.swing.JComboBox jcbtrueroi25;
    private javax.swing.JComboBox jcbtrueroi26;
    private javax.swing.JComboBox jcbtrueroi27;
    private javax.swing.JComboBox jcbtrueroi28;
    private javax.swing.JComboBox jcbtrueroi29;
    private javax.swing.JComboBox jcbtrueroi3;
    private javax.swing.JComboBox jcbtrueroi30;
    private javax.swing.JComboBox jcbtrueroi31;
    private javax.swing.JComboBox jcbtrueroi32;
    private javax.swing.JComboBox jcbtrueroi33;
    private javax.swing.JComboBox jcbtrueroi34;
    private javax.swing.JComboBox jcbtrueroi35;
    private javax.swing.JComboBox jcbtrueroi36;
    private javax.swing.JComboBox jcbtrueroi37;
    private javax.swing.JComboBox jcbtrueroi38;
    private javax.swing.JComboBox jcbtrueroi39;
    private javax.swing.JComboBox jcbtrueroi4;
    private javax.swing.JComboBox jcbtrueroi40;
    private javax.swing.JComboBox jcbtrueroi5;
    private javax.swing.JComboBox jcbtrueroi6;
    private javax.swing.JComboBox jcbtrueroi7;
    private javax.swing.JComboBox jcbtrueroi8;
    private javax.swing.JComboBox jcbtrueroi9;
    // End of variables declaration//GEN-END:variables
}
